### ISSUE TITLE
Cant access firmware from link. 

### ISSUE THREAD

**Issue by EthanHayes77** [kunsteak/The-Kunst-Keyboard#2]
When i tap the link I cant access the firmware. Error 404 pops up. Can u repost it, or get it in a different way? Thanks

**Comment by kunsteak** [comment]
Hey Ethan! Let me know which files you need and I'll send 'em to ya... re-uploading doesn't seem to help!

**Comment by EthanHayes77** [comment]
Awesome, im looking for the firmware files to flash onto each side of the boards. and a reset file if u have it. Thanks

**Comment by EthanHayes77** [comment]
To specify more, I will be using 2 nice!nanov2s so whatever firmware files for them that's needed. Thanks

**Comment by EthanHayes77** [comment]
Awesome, I’m looking for the w firmware files to flash onto each side of the boards. And a reset file if u have. Thanks To specify more, I’ll be using 2 nice!nanov2s so whatever firmware files for them that’s needed. Thanks.Sent from my iPhoneOn Jun 24, 2023, at 12:50 PM, Kunsteak ***@***.***> wrote:﻿
Hey Ethan! Let me know which files you need and I'll send 'em to ya

**Comment by kunsteak** [comment]
The firmware files are available here: https://github.com/kunsteak/zmk-config-kunst/actions/runs/3351803977

**Comment by EthanHayes77** [comment]
Sorry, but when I look at the workflow and at the spot that says firmware, it says expired next to it, not letting me click on it. Is there something im missing here. Im pretty new to this sorry. EDIT, Ok ive just forked it then made my own repo I think, and now I was able to downloadhe firmware. What firmware should I be using for wireless with nice!nanov2s? Im guessing the 2 "norm" ones right? not the 3 "dongle" ones...

**Comment by kunsteak** [comment]
You'll have to clone the repo and add a random file, then commit and push that to your own account. Once you do that you'll have your own firmware under "Actions".

**Comment by EthanHayes77** [comment]
Yep just did that, I now have the firmware files, for wireless with Nice!nanos i should be using the 2 "norm" files right? and not the "dongle" files correct?

**Comment by kunsteak** [comment]
Correct! Have fun!
